dist: xenial
sudo: required
language: python
python:
  - '3.6'
  - '3.7'
services:
  - docker
before_install:
  - docker pull univa/tortuga-builder
install:
  - docker run -it --rm -v `pwd`:/tortuga univa/tortuga-builder
script:
  - docker run -it --rm -v `pwd`:/tortuga univa/tortuga-builder tox -c src/core/tox.ini
  - docker run -it --rm -v `pwd`:/tortuga univa/tortuga-builder tox -c src/installer/tox.ini
  - docker run -it --rm -v `pwd`:/tortuga univa/tortuga-builder chown -R `id -u`:`id -g` ./install
  - cp -f docker/*.build-kit install
  - docker build -t univa/tortuga-build-kit:$TRAVIS_BUILD_NUMBER -f ./install/Dockerfile.build-kit ./install
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/docker_push.sh
    on:
      repo: UnivaCorporation/tortuga
      all_branches: true
  - provider: releases
    api_key:
      secure: gD2c3gzpbiQSff8Ebk9yM1xc8kbG2divgEpC6Bw5KyvcfL2mhNImHimKtqvm6WWbhRvXr8ACfs5mreeWQ917FQ5Jr1iAQHeBx6qeA/fY44B9aVjkae6TLDB3FVktQ63CWYsaGiLd3YCR7STOvp7msUuU2h1LFD76KfqCFRm0RICsoT5IdUjVAeYHdtcJtxEh267IOMDMWn2LJ8g+B06JK9SZYyOkYSHBGOTwPC5g9sbiE86PF8OxZ7SY2an83zJg1QRJp2crww4yrX4/59ErLRPNR38hM2v9aD6k+rXIKovF/OBBkQ2WotggpKvLIICSDirnnK/TuDglK33t0CH7bgPOO8kjLYqQ3km7YlpbJqQqb9QDx3cZNTg6poRPrHdE5vnMTSggOSYjOuWh8j81sBYTeMI4sJpuBplKiLx8FtnNXXEtP9ENjmoodrug1tVkisUCb6LPPrrHhKElEcPqA1Dbo0/qaqMHdyw08lklmBFECYYEc+4+ljayM0uYB908+ele2mv0a1Rv9VypOy6oWpM+mbk5JeQOSCns4iPUULCP4YuDMcvKctTu8g4NJpMrqwf6j3EuWmFUJY6B/48CoQlkaSr0a8GMu8kV1/hPnskNW+ZReWeVYc8eCttDCpC213WlEsDod2AKFepDt2lpHs+CIhZHtiNZNhFLAucUN28=
    file_glob: true
    file: "dist/tortuga*.tar.bz2"
    skip_cleanup: true
    draft: true
    on:
      repo: UnivaCorporation/tortuga
      all_branches: true
      tags: true
